# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
array = [
      ["United States of America - United States Dollar (USD)", "USD"],
      ["European Union - Euro (EUR)", "EUR"],
      ["Afghanistan - Afghan Afghani (AFN)", "AFN"],
      ["Albania - Albanian Lek (ALL)", "ALL"],
      ["Algeria - Algerian Dinar (DZD)", "DZD"],
      ["Angola - Angolan Kwanza (AOA)", "AOA"],
      ["Anguilla - East Caribbean Dollar (XCD)", "XCD"],
      ["Antigua and Barbuda - East Caribbean Dollar (XCD)", "XCD"],
      ["Argentina - Argentine Peso (ARS)", "ARS"],
      ["Armenia - Armenian Dram (AMD)", "AMD"],
      ["Aruba - Aruban Florin (AWG)", "AWG"],
      ["Australia - Australian Dollar (AUD)", "AUD"],
      ["Azerbaijan - Azerbaijani Manat (AZN)", "AZN"],
      ["Bahamas - Bahamian Dollar (BSD)", "BSD"],
      ["Bahrain - Bahraini Dinar (BHD)", "BHD"],
      ["Bangladesh - Bangladeshi Taka (BDT)", "BDT"],
      ["Barbados - Barbadian Dollar (BBD)", "BBD"],
      ["Belarus - Belarusian Ruble (BYR)", "BYR"],
      ["Belize - Belize Dollar (BZD)", "BZD"],
      ["Benin - West African CFA Franc (XOF)", "XOF"],
      ["Bhutan - Bhutanese Ngultrum (BTN)", "BTN"],
      ["Bolivia - Bolivian Boliviano (BOB)", "BOB"],
      ["Bosnia-Herzegovina - Bosnia and Herzegovina Konvertibilna marka (BAM)", "BAM"],
      ["Botswana - Botswana Pula (BWP)", "BWP"],
      ["Brazil - Brazilian Real (BRL)", "BRL"],
      ["Brunei - Brunei Dollar (BND)", "BND"],
      ["Bulgaria - Bulgarian Lev (BGN)", "BGN"],
      ["Burkina Faso - West African CFA Franc (XOF)", "XOF"],
      ["Burundi - Burundi Franc (BIF)", "BIF"],
      ["Cambodia - Cambodian Riel (KHR)", "KHR"],
      ["Cameroon - Central African CFA Franc (XAF)", "XAF"],
      ["Canada - Canadian Dollar (CAD)", "CAD"],
      ["Cape Verde - Cape Verdean Escudo (CVE)", "CVE"],
      ["Cayman Islands - Cayman Islands Dollar (KYD)", "KYD"],
      ["Central African Republic - Central African CFA Franc (XAF)", "XAF"],
      ["Chad - Central African CFA Franc (XAF)", "XAF"],
      ["Chile - Chilean Peso (CLP)", "CLP"],
      ["China - Chinese Yuan (CNY)", "CNY"],
      ["Colombia - Colombian Peso (COP)", "COP"],
      ["Comoros - Comorian Franc (KMF)", "KMF"],
      ["Congo - Central African CFA Franc (XAF)", "XAF"],
      ["Congo, Democratic Republic - Congolese Franc (CDF)", "CDF"],
      ["Costa Rica - Costa Rican Colon (CRC)", "CRC"],
      ["Cote d'Ivoire - West African CFA Franc (XOF)", "XOF"],
      ["Croatia - Croatian Kuna (HRK)", "HRK"],
      ["Cuba - Cuban Peso (CUC)", "CUC"],
      ["Czech Republic - Czech Koruna (CZK)", "CZK"],
      ["Denmark - Danish Krone (DKK)", "DKK"],
      ["Djibouti - Djiboutian Franc (DJF)", "DJF"],
      ["Dominica - East Caribbean Dollar (XCD)", "XCD"],
      ["Dominican Republic - Dominican Peso (DOP)", "DOP"],
      ["Egypt - Egyptian Pound (EGP)", "EGP"],
      ["Equatorial Guinea - Central African CFA Franc (GQE)", "GQE"],
      ["Eritrea - Eritrean Nakfa (ERN)", "ERN"],
      ["Estonia - Estonian Kroon (EEK)", "EEK"],
      ["Ethiopia - Ethiopian Birr (ETB)", "ETB"],
      ["Falkland Islands - Falkland Islands Pound (FKP)", "FKP"],
      ["Fiji - Fijian Dollar (FJD)", "FJD"],
      ["French Polynesia - CFP Franc (XPF)", "XPF"],
      ["Gabon - Central African CFA Franc (XAF)", "XAF"],
      ["Gambia - Gambian Dalasi (GMD)", "GMD"],
      ["Georgia - Georgian Lari (GEL)", "GEL"],
      ["Ghana - Ghanaian Cedi (GHS)", "GHS"],
      ["Gibraltar - Gibraltar Pound (GIP)", "GIP"],
      ["Grenada - East Caribbean Dollar (XCD)", "XCD"],
      ["Guatemala - Guatemalan Quetzal (GTQ)", "GTQ"],
      ["Guinea - Guinean Franc (GNF)", "GNF"],
      ["Guinea-Bissau - West African CFA Franc (XOF)", "XOF"],
      ["Guyana - Guyanese Dollar (GYD)", "GYD"],
      ["Haiti - Haitian Gourde (HTG)", "HTG"],
      ["Honduras - Honduran Lempira (HNL)", "HNL"],
      ["Hong Kong - Hong Kong Dollar (HKD)", "HKD"],
      ["Hungary - Hungarian Forint (HUF)", "HUF"],
      ["Iceland - Icelandic Krona (ISK)", "ISK"],
      ["India - Indian Rupee (INR)", "INR"],
      ["Indonesia - Indonesian Rupiah (IDR)", "IDR"],
      ["International Monetary Fund - Special Drawing Rights (XDR)", "XDR"],
      ["Iran - Iranian Rial (IRR)", "IRR"],
      ["Iraq - Iraqi Dinar (IQD)", "IQD"],
      ["Israel - Israeli new Sheqel (ILS)", "ILS"],
      ["Jamaica - Jamaican Dollar (JMD)", "JMD"],
      ["Japan - Japanese Yen (JPY)", "JPY"],
      ["Jordan - Jordanian Dinar (JOD)", "JOD"],
      ["Kazakhstan - Kazakhstani Tenge (KZT)", "KZT"],
      ["Kenya - Kenyan Shilling (KES)", "KES"],
      ["Kiribati - Australian Dollar (AUD)", "AUD"],
      ["Korea North - North Korean Won  (KPW)", "KPW"],
      ["Korea South - South Korean Won  (KRW)", "KRW"],
      ["Kuwait - Kuwaiti Dinar (KWD)", "KWD"],
      ["Kyrgyzstan - Kyrgyzstani Som (KGS)", "KGS"],
      ["Laos - Lao Kip (LAK)", "LAK"],
      ["Latvia - Latvian Lats (LVL)", "LVL"],
      ["Lebanon - Lebanese Lira (LBP)", "LBP"],
      ["Lesotho - Lesotho Loti (LSL)", "LSL"],
      ["Liberia - Liberian Dollar (LRD)", "LRD"],
      ["Libya - Libyan Dinar (LYD)", "LYD"],
      ["Liechtenstein - Swiss Franc (CHF)", "CHF"],
      ["Lithuania - Lithuanian Litas (LTL)", "LTL"],
      ["Macau - Macanese Pataca (MOP)", "MOP"],
      ["Macedonia (Former Yug. Rep.) - Macedonian Denar (MKD)", "MKD"],
      ["Madagascar - Malagasy Ariary (MGA)", "MGA"],
      ["Malawi - Malawian Kwacha (MWK)", "MWK"],
      ["Malaysia - Malaysian Ringgit (MYR)", "MYR"],
      ["Maldives - Maldivian Rufiyaa (MVR)", "MVR"],
      ["Mali - West African CFA Franc (XOF)", "XOF"],
      ["Mauritania - Mauritanian Ouguiya (MRO)", "MRO"],
      ["Mauritius - Mauritian Rupee (MUR)", "MUR"],
      ["Mexico - Mexican Peso (MXN)", "MXN"],
      ["Moldova - Moldovan Leu (MDL)", "MDL"],
      ["Mongolia - Mongolian Tugrik (MNT)", "MNT"],
      ["Montserrat - East Caribbean Dollar (XCD)", "XCD"],
      ["Morocco - Moroccan Dirham (MAD)", "MAD"],
      ["Mozambique - Mozambican Metical (MZM)", "MZM"],
      ["Myanmar - Myanma Kyat (MMK)", "MMK"],
      ["Namibia - Namibian Dollar (NAD)", "NAD"],
      ["Nauru - Australian Dollar (AUD)", "AUD"],
      ["Nepal - Nepalese Rupee (NPR)", "NPR"],
      ["Netherlands Antilles - Netherlands Antillean Gulden (ANG)", "ANG"],
      ["New Caledonia - CFP Franc (XPF)", "XPF"],
      ["New Zealand - New Zealand Dollar (NZD)", "NZD"],
      ["Nicaragua - Nicaraguan Cordoba (NIO)", "NIO"],
      ["Niger - West African CFA Franc (XOF)", "XOF"],
      ["Nigeria - Nigerian Naira (NGN)", "NGN"],
      ["Norway - Norwegian Krone (NOK)", "NOK"],
      ["Oman - Omani Rial (OMR)", "OMR"],
      ["Pakistan - Pakistani Rupee (PKR)", "PKR"],
      ["Panama - Panamanian Balboa (PAB)", "PAB"],
      ["Papua New Guinea - Papua New Guinean Kina (PGK)", "PGK"],
      ["Paraguay - Paraguayan Guarani (PYG)", "PYG"],
      ["Peru - Peruvian nuevo Sol (PEN)", "PEN"],
      ["Philippines - Philippine Peso (PHP)", "PHP"],
      ["Poland - Polish Zloty (PLN)", "PLN"],
      ["Qatar - Qatari Riyal (QAR)", "QAR"],
      ["Romania - Romanian Leu (RON)", "RON"],
      ["Russia - Russian Ruble (RUB)", "RUB"],
      ["Rwanda - Rwandan Franc (RWF)", "RWF"],
      ["Saint Helena - Saint Helena Pound (SHP)", "SHP"],
      ["Saint Kitts and Nevis - East Caribbean Dollar (XCD)", "XCD"],
      ["Saint Lucia - East Caribbean Dollar (XCD)", "XCD"],
      ["Saint Vincent and the Grenadines - East Caribbean Dollar (XCD)", "XCD"],
      ["Samoa (Western) - Samoan Tala (WST)", "WST"],
      ["Sao Tome and Principe - Sao Tome and Principe Dobra (STD)", "STD"],
      ["Saudi Arabia - Saudi Riyal (SAR)", "SAR"],
      ["Senegal - West African CFA Franc (XOF)", "XOF"],
      ["Serbia - Serbian Dinar (RSD)", "RSD"],
      ["Seychelles - Seychellois Rupee (SCR)", "SCR"],
      ["Sierra Leone - Sierra Leonean Leone (SLL)", "SLL"],
      ["Singapore - Singapore Dollar (SGD)", "SGD"],
      ["Slovakia - Slovak Koruna (SKK)", "SKK"],
      ["Solomon Islands - Solomon Islands Dollar (SBD)", "SBD"],
      ["Somalia - Somali Shilling (SOS)", "SOS"],
      ["South Africa - South African Rand (ZAR)", "ZAR"],
      ["South Sudan - Sudanese Pound (SDG)", "SDG"],
      ["Sri Lanka - Sri Lankan Rupee (LKR)", "LKR"],
      ["Sudan - Sudanese Pound (SDG)", "SDG"],
      ["Suriname - Surinamese Dollar (SRD)", "SRD"],
      ["Swaziland - Swazi Lilangeni (SZL)", "SZL"],
      ["Sweden - Swedish Krona (SEK)", "SEK"],
      ["Switzerland - Swiss Franc (CHF)", "CHF"],
      ["Syria - Syrian Pound (SYP)", "SYP"],
      ["Taiwan - New Taiwan Dollar (TWD)", "TWD"],
      ["Tajikistan - Tajikistani Somoni (TJS)", "TJS"],
      ["Tanzania - Tanzanian Shilling (TZS)", "TZS"],
      ["Thailand - Thai Baht (THB)", "THB"],
      ["Togo - West African CFA Franc (XOF)", "XOF"],
      ["Tonga - Tongan Paanga (TOP)", "TOP"],
      ["Trinidad and Tobago - Trinidad and Tobago Dollar (TTD)", "TTD"],
      ["Tunisia - Tunisian Dinar (TND)", "TND"],
      ["Turkey - Turkish new Lira (TRY)", "TRY"],
      ["Turkmenistan - Turkmen Manat (TMM)", "TMM"],
      ["Tuvalu - Australian Dollar (AUD)", "AUD"],
      ["Uganda - Ugandan Shilling (UGX)", "UGX"],
      ["Ukraine - Ukrainian Hryvnia (UAH)", "UAH"],
      ["United Arab Emirates - UAE -Dirham (AED)", "AED"],
      ["United Kingdom - British Pound (GBP)", "GBP"],
      ["Uruguay - Uruguayan Peso (UYU)", "UYU"],
      ["Uzbekistan - Uzbekistani Som (UZS)", "UZS"],
      ["Vanuatu - Vanuatu Vatu (VUV)", "VUV"],
      ["Venezuela - Venezuelan Bolivar (VEB)", "VEB"],
      ["Vietnam - Vietnamese Dong (VND)", "VND"],
      ["Wallis and Futuna Islands - CFP Franc (XPF)", "XPF"],
      ["Yemen - Yemeni Rial (YER)", "YER"],
      ["Zambia - Zambian Kwacha (ZMK)", "ZMK"],
      ["Zimbabwe - Zimbabwean Dollar (ZWD)", "ZWD"],
    ]

array.each do |arr|
  Currency.create!(country_name: arr.first, name: arr.last)
end
