# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
array = [
      ["United States of America  United States - dollar  (USD)", "USD"],
      ["European - euro (EUR)", "EUR"],
      ["Afghanistan Afghan - afghani  (AFN)", "AFN"],
      ["Albania Albanian - lek  (ALL)", "ALL"],
      ["Algeria Algerian - dinar  (DZD)", "DZD"],
      ["Angola  Angolan - kwanza  (AOA)", "AOA"],
      ["Anguilla  East Caribbean - dollar (XCD)", "XCD"],
      ["Antigua and Barbuda East Caribbean - dollar (XCD)", "XCD"],
      ["Argentina Argentine - peso  (ARS)", "ARS"],
      ["Armenia Armenian - dram (AMD)", "AMD"],
      ["Aruba Aruban - florin (AWG)", "AWG"],
      ["Australia Australian - dollar (AUD)", "AUD"],
      ["Azerbaijan  Azerbaijani - manat (AZN)", "AZN"],
      ["Bahamas Bahamian - dollar (BSD)", "BSD"],
      ["Bahrain Bahraini - dinar  (BHD)", "BHD"],
      ["Bangladesh  Bangladeshi - taka  (BDT)", "BDT"],
      ["Barbados  Barbadian - dollar  (BBD)", "BBD"],
      ["Belarus Belarusian - ruble  (BYR)", "BYR"],
      ["Belize  Belize - dollar (BZD)", "BZD"],
      ["Benin West African CFA - franc  (XOF)", "XOF"],
      ["Bhutan  Bhutanese - ngultrum  (BTN)", "BTN"],
      ["Bolivia Bolivian - boliviano  (BOB)", "BOB"],
      ["Bosnia-Herzegovina  Bosnia and Herzegovina - konvertibilna marka (BAM)", "BAM"],
      ["Botswana  Botswana - pula (BWP)", "BWP"],
      ["Brazil  Brazilian - real  (BRL)", "BRL"],
      ["Brunei  Brunei - dollar (BND)", "BND"],
      ["Bulgaria  Bulgarian - lev (BGN)", "BGN"],
      ["Burkina Faso  West African CFA - franc  (XOF)", "XOF"],
      ["Burundi Burundi - franc (BIF)", "BIF"],
      ["Cambodia  Cambodian - riel  (KHR)", "KHR"],
      ["Cameroon  Central African CFA - franc (XAF)", "XAF"],
      ["Canada  Canadian - dollar (CAD)", "CAD"],
      ["Cape Verde  Cape Verdean - escudo (CVE)", "CVE"],
      ["Cayman Islands  Cayman Islands - dollar (KYD)", "KYD"],
      ["Central African Republic  Central African CFA - franc (XAF)", "XAF"],
      ["Chad  Central African CFA - franc (XAF)", "XAF"],
      ["Chile Chilean - peso  (CLP)", "CLP"],
      ["China Chinese - renminbi  (CNY)", "CNY"],
      ["Colombia  Colombian - peso  (COP)", "COP"],
      ["Comoros Comorian - franc  (KMF)", "KMF"],
      ["Congo Central African CFA - franc (XAF)", "XAF"],
      ["Congo, Democratic Republic  Congolese - franc (CDF)", "CDF"],
      ["Costa Rica  Costa Rican - colon (CRC)", "CRC"],
      ["Cote d'Ivoire West African CFA - franc  (XOF)", "XOF"],
      ["Croatia Croatian - kuna (HRK)", "HRK"],
      ["Cuba  Cuban - peso  (CUC)", "CUC"],
      ["Czech Republic  Czech - koruna  (CZK)", "CZK"],
      ["Denmark Danish - krone  (DKK)", "DKK"],
      ["Djibouti  Djiboutian - franc  (DJF)", "DJF"],
      ["Dominica  East Caribbean - dollar (XCD)", "XCD"],
      ["Dominican Republic  Dominican - peso  (DOP)", "DOP"],
      ["Egypt Egyptian - pound  (EGP)", "EGP"],
      ["Equatorial Guinea Central African CFA - franc (GQE)", "GQE"],
      ["Eritrea Eritrean - nakfa  (ERN)", "ERN"],
      ["Estonia Estonian - kroon  (EEK)", "EEK"],
      ["Ethiopia  Ethiopian - birr  (ETB)", "ETB"],
      ["Falkland Islands  Falkland Islands - pound  (FKP)", "FKP"],
      ["Fiji  Fijian - dollar (FJD)", "FJD"],
      ["French Polynesia  CFP - franc (XPF)", "XPF"],
      ["Gabon Central African CFA - franc (XAF)", "XAF"],
      ["Gambia  Gambian - dalasi  (GMD)", "GMD"],
      ["Georgia Georgian - lari (GEL)", "GEL"],
      ["Ghana Ghanaian - cedi (GHS)", "GHS"],
      ["Gibraltar Gibraltar - pound (GIP)", "GIP"],
      ["Grenada East Caribbean - dollar (XCD)", "XCD"],
      ["Guatemala Guatemalan - quetzal  (GTQ)", "GTQ"],
      ["Guinea  Guinean - franc (GNF)", "GNF"],
      ["Guinea-Bissau West African CFA - franc  (XOF)", "XOF"],
      ["Guyana  Guyanese - dollar (GYD)", "GYD"],
      ["Haiti Haitian - gourde  (HTG)", "HTG"],
      ["Honduras  Honduran - lempira  (HNL)", "HNL"],
      ["Hong Kong Hong Kong - dollar  (HKD)", "HKD"],
      ["Hungary Hungarian - forint  (HUF)", "HUF"],
      ["Iceland Icelandic - krona (ISK)", "ISK"],
      ["India Indian - rupee  (INR)", "INR"],
      ["Indonesia Indonesian - rupiah (IDR)", "IDR"],
      ["International Monetary Fund Special Drawing - Rights  (XDR)", "XDR"],
      ["Iran  Iranian - rial  (IRR)", "IRR"],
      ["Iraq  Iraqi - dinar (IQD)", "IQD"],
      ["Israel  Israeli new - sheqel  (ILS)", "ILS"],
      ["Jamaica Jamaican - dollar (JMD)", "JMD"],
      ["Japan Japanese - yen  (JPY)", "JPY"],
      ["Jordan  Jordanian - dinar (JOD)", "JOD"],
      ["Kazakhstan  Kazakhstani - tenge (KZT)", "KZT"],
      ["Kenya Kenyan - shilling (KES)", "KES"],
      ["Kiribati  Australian - dollar (AUD)", "AUD"],
      ["Korea North North Korean - won  (KPW)", "KPW"],
      ["Korea South South Korean - won  (KRW)", "KRW"],
      ["Kuwait  Kuwaiti - dinar (KWD)", "KWD"],
      ["Kyrgyzstan  Kyrgyzstani - som (KGS)", "KGS"],
      ["Laos  Lao - kip (LAK)", "LAK"],
      ["Latvia  Latvian - lats  (LVL)", "LVL"],
      ["Lebanon Lebanese - lira (LBP)", "LBP"],
      ["Lesotho Lesotho - loti  (LSL)", "LSL"],
      ["Liberia Liberian - dollar (LRD)", "LRD"],
      ["Libya Libyan - dinar  (LYD)", "LYD"],
      ["Liechtenstein uses the Swiss - Franc  (CHF)", "CHF"],
      ["Lithuania Lithuanian - litas  (LTL)", "LTL"],
      ["Macau Macanese - pataca (MOP)", "MOP"],
      ["Macedonia (Former Yug. Rep.)  Macedonian - denar  (MKD)", "MKD"],
      ["Madagascar  Malagasy - ariary (MGA)", "MGA"],
      ["Malawi  Malawian - kwacha (MWK)", "MWK"],
      ["Malaysia  Malaysian - ringgit (MYR)", "MYR"],
      ["Maldives  Maldivian - rufiyaa (MVR)", "MVR"],
      ["Mali  West African CFA - franc  (XOF)", "XOF"],
      ["Mauritania  Mauritanian - ouguiya (MRO)", "MRO"],
      ["Mauritius Mauritian - rupee (MUR)", "MUR"],
      ["Mexico  Mexican - peso  (MXN)", "MXN"],
      ["Moldova Moldovan - leu  (MDL)", "MDL"],
      ["Mongolia  Mongolian - tugrik  (MNT)", "MNT"],
      ["Montserrat  East Caribbean - dollar (XCD)", "XCD"],
      ["Morocco Moroccan - dirham (MAD)", "MAD"],
      ["Mozambique  Mozambican - metical  (MZM)", "MZM"],
      ["Myanmar Myanma - kyat (MMK)", "MMK"],
      ["Namibia Namibian - dollar (NAD)", "NAD"],
      ["Nauru Australian - dollar (AUD)", "AUD"],
      ["Nepal Nepalese - rupee  (NPR)", "NPR"],
      ["Netherlands Antilles  Netherlands Antillean - gulden  (ANG)", "ANG"],
      ["New Caledonia CFP - franc (XPF)", "XPF"],
      ["New Zealand New Zealand - dollar  (NZD)", "NZD"],
      ["Nicaragua Nicaraguan - cordoba  (NIO)", "NIO"],
      ["Niger West African CFA - franc  (XOF)", "XOF"],
      ["Nigeria Nigerian - naira  (NGN)", "NGN"],
      ["Norway  Norwegian - krone (NOK)", "NOK"],
      ["Oman  Omani - rial  (OMR)", "OMR"],
      ["Pakistan  Pakistani - rupee (PKR)", "PKR"],
      ["Panama  Panamanian - balboa (PAB)", "PAB"],
      ["Papua New Guinea  Papua New Guinean - kina  (PGK)", "PGK"],
      ["Paraguay  Paraguayan - guarani  (PYG)", "PYG"],
      ["Peru  Peruvian nuevo - sol  (PEN)", "PEN"],
      ["Philippines Philippine - peso (PHP)", "PHP"],
      ["Poland  Polish - zloty  (PLN)", "PLN"],
      ["Qatar Qatari - riyal  (QAR)", "QAR"],
      ["Romania Romanian - leu  (RON)", "RON"],
      ["Russia  Russian - ruble (RUB)", "RUB"],
      ["Rwanda  Rwandan - franc (RWF)", "RWF"],
      ["Saint Helena  Saint Helena - pound  (SHP)", "SHP"],
      ["Saint Kitts and Nevis East Caribbean - dollar (XCD)", "XCD"],
      ["Saint Lucia East Caribbean - dollar (XCD)", "XCD"],
      ["Saint Vincent and the Grenadines  East Caribbean - dollar (XCD)", "XCD"],
      ["Samoa (Western) Samoan - tala (WST)", "WST"],
      ["Sao Tome and Principe Sao Tome and Principe - dobra (STD)", "STD"],
      ["Saudi Arabia  Saudi - riyal (SAR)", "SAR"],
      ["Senegal West African CFA - franc  (XOF)", "XOF"],
      ["Serbia  Serbian - dinar (RSD)", "RSD"],
      ["Seychelles  Seychellois - rupee (SCR)", "SCR"],
      ["Sierra Leone  Sierra Leonean - leone  (SLL)", "SLL"],
      ["Singapore Singapore - dollar  (SGD)", "SGD"],
      ["Slovakia  Slovak - koruna (SKK)", "SKK"],
      ["Solomon Islands Solomon Islands - dollar  (SBD)", "SBD"],
      ["Somalia Somali - shilling (SOS)", "SOS"],
      ["South Africa  South African - rand  (ZAR)", "ZAR"],
      ["South Sudan Sudanese - pound  (SDG)", "SDG"],
      ["Sri Lanka Sri Lankan - rupee  (LKR)", "LKR"],
      ["Sudan Sudanese - pound  (SDG)", "SDG"],
      ["Suriname  Surinamese - dollar (SRD)", "SRD"],
      ["Swaziland Swazi - lilangeni (SZL)", "SZL"],
      ["Sweden  Swedish - krona (SEK)", "SEK"],
      ["Switzerland Swiss - franc (CHF)", "CHF"],
      ["Syria Syrian - pound (SYP)", "SYP"],
      ["Taiwan  New Taiwan - dollar (TWD)", "TWD"],
      ["Tajikistan  Tajikistani - somoni (TJS)", "TJS"],
      ["Tanzania  Tanzanian - shilling (TZS)", "TZS"],
      ["Thailand  Thai - baht (THB)", "THB"],
      ["Togo  West African CFA - franc (XOF)", "XOF"],
      ["Tonga - Paanga  (TOP)", "TOP"],
      ["Trinidad and Tobago Trinidad and Tobago - dollar  (TTD)", "TTD"],
      ["Tunisia Tunisian - dinar  (TND)", "TND"],
      ["Turkey  Turkish new - lira  (TRY)", "TRY"],
      ["Turkmenistan  Turkmen - manat (TMM)", "TMM"],
      ["Tuvalu  Australian - dollar (AUD)", "AUD"],
      ["Uganda  Ugandan - shilling  (UGX)", "UGX"],
      ["Ukraine Ukrainian - hryvnia (UAH)", "UAH"],
      ["United Arab Emirates  UAE - dirham  (AED)", "AED"],
      ["United Kingdom  British - pound (GBP)", "GBP"],
      ["Uruguay Uruguayan - peso  (UYU)", "UYU"],
      ["Uzbekistan  Uzbekistani - som (UZS)", "UZS"],
      ["Vanuatu Vanuatu - vatu  (VUV)", "VUV"],
      ["Venezuela Venezuelan - bolivar  (VEB)", "VEB"],
      ["Vietnam Vietnamese - dong (VND)", "VND"],
      ["Wallis and Futuna Islands CFP - franc (XPF)", "XPF"],
      ["Yemen Yemeni - rial (YER)", "YER"],
      ["Zambia  Zambian - kwacha  (ZMK)", "ZMK"],
      ["Zimbabwe  Zimbabwean - dollar (ZWD)", "ZWD"],
    ]

array.each do |arr|
  Currency.create!(country_name: arr.first, name: arr.last)
end